fernando-mc/serverless-finch

index.js
References this issue: https://github.com/fernando-mc/serverless-finch/issues/9
Adds the command `serverless client remove` which empties the bucket and removes it. Some notes:
1) I refactored to make use of the functions that finds and empties the bucket from the `deploy` command. Im not overly familiar with the Class-style syntax in JS these days, so let me know what you think
2) I also added an arbitary 3 second delay to the remove process, as its clearly a very destructive process! Not sure if thats overkill though, thoughts?
=> Add functionality to remove bucket

README.md, index.js
Thanks for this useful repository :)
This pr close #5.
If the user do not set the `distributionFolder` it will have the current behavior: deploy the `client/dist` folder.
For example this will work for create-react-app:
```
plugins:
- serverless-finch
custom:
client:
bucketName: s3-bucketname-serverless-graphql-apollo
distributionFolder: build
```
=> Upload static website files from custom directory

index.js
* Correctly display s3 url based on the formats laid out for specific regions in the documentation.
* Add a log the subdomained version of the url
These changes were made according to the documentation on these pages:
* http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html
* http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html
* http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_website_region_endpoints
This relates to, includes, and expands upon the changes in #6
=> Include dynamic and additional URL formats

index.js
These point to the solution:
* https://forum.serverless.com/t/serverless-plugin-resolving-variable-references/2233/2
* https://github.com/serverless/serverless/pull/3911/files
TL;DR: dschep wrote "Serverless changed it’s behavior a few releases
ago. That variable substitution is not called by the time plugin
constructors get called. Unless you actually need it then, just access
it in your lifecycle hooks, it’ should be resolved by then."
=> Fix GH-17 variables do not get expanded

README.md, index.js
Added three .yml options: 'indexDocument' and 'errorDocument', which allow customizing the s3 bucket option for each, and 'spa', which automatically sets the errorDocument to be the indexDocument, overriding the errorDocument .yml setting if both are set.
This implements the issue at https://github.com/fernando-mc/serverless-finch/issues/16
=> Implement Feature Request: Add custom fields to define index and error documents

index.js
As described in #41, our calls to the AWS SDK `request` method use the old API, which has arguments for region and stage. The new API does not support these arguments, instead storing the region and stage elsewhere. Instead there is an optional `options` argument (which we don't need for anything in serverless-finch at the moment). Region and stage are set at initialization.
Change all calls to `aws.request` to remove the region and stage arguments. Example:
```js
return this.aws.request('S3', 'putObject', params, this.stage, this.region);
```
```js
return this.aws.request('S3', 'putObject', params);
```
=> update calls to aws.request to use new API (fixes #41)

README.md, index.js, lib/validate.js
A test @fernando-mc did on the recent refactor PR (#43) uncovered a scenario where the `serverless.yml` validation step was not working properly and causing an ungaught exception later down the line. 
It turns out that the problem was that the `validateClient` function in `llib/validate.js` was tying to return errors but failing because some of the return statements were in `forEach` loops, which meant that if those pieces didn't validate we would still continue as if they were valid.
Also, the README had not yet been updated with the new `name`/`value` terminology for `objectHeaders` rather than the original `headerName` and `headerValue`
I updated the `validateClient` function to throw errors rather than returning errors, as well as updating a little piece of logic in the …
=> Fix validator bug

README.md, index.js
See comments regarding confirmation prompt in (already closed) #47.
For automated builds the confirmation prompt would stall the process. 
The new --no-confirm CLI option allows scripts to disable the prompt for automated builds.
=> Added CLI option to disable confirmation prompt and updated README

lib/upload.js
Fixes bug described in #51 
Replace system-native path separators with '/' for AWS key
I was able to replicate the bug on my Windows machine. This PR fixes the issue on Windows for me. It also still passes manual checks on Ubuntu.
@fernando-mc 
@cloudandcode
=> make sure path seperators are '/' in S3 key (fixes #51)

README.md, lib/upload.js, package.json
Allow glob pattern (wildcards) usage when adding headers.
So, we can add headers to all html files or any other kinds of files:
```yaml
custom:
client:
...
objectHeaders:
'*.html':
- name: [header-name]
value: [header-value]
...
... [more file- or folder-specific rules]
...
```
=> Allow glob pattern to add headers to matching files

README.md, index.js, lib/upload.js
Hi, I've attempted to fix issue #63.
Adds configuration option 'uploadOrder' as a list of case insensitive regex's.  They're in order of first to upload to last, with later matches overriding the earlier. Therefore it would be best to start with more
generic regex's to more specific.
In the implementation instead of it uploading all files in one set of promises, it bunches up files into order groups and uploads the groups sequentially.
=> adds uploadOrder configuration

README.md
Since `[some/path/here.json]` translates to `["some/path/here.json"]` it is confusing and I thought the policy required an array of strings.
Update the README and us `"some/path/policy.json"` instead. Also added some tips about env paths since finch will try and look in serverless-finch module directory path for relative path policies.
=> Give more instructions on bucket policy.

index.js, lib/bucketUtils.js, lib/upload.js, lib/validate.js
I've got a need for the keyPrefix mentioned in #73, so this is a little attempt at adding that. :) 
Adding a keyPrefix option, so that it's possibly to upload files to a prefixed s3 path.
[@ mentions of other contributors]
=> Add a keyPrefix option

lib/upload.js
Fixes https://github.com/fernando-mc/serverless-finch/issues/86 (Deep upload paths specified with keyPrefix get resolved incorrectly
Flattening the fileKey array before doing a `.join('/')` results in a correct expected behaviour.
@fernando-mc
=> fix: deep upload paths are incorrectly resolved (e.g. with keyPrefix 'a/b' path resolves to 'a,b')

README.md, index.js, lib/upload.js
Currently uploding files to a bucket that requires server side encryption is not possible. This feature adds support for these use cases.
- optional `sse` option in which the encryption algorithm can be defined
=> Add support for Server Side Encryption of uploaded files

lib/bucketUtils.js
When using the `keyPrefix` option along with having bucket deletion enabled, the following error occurs if the key prefix does not already exist:
```
ServerlessError: The XML you provided was not well-formed or did not validate against our published schema
```
Closes #85 
The issue was with the `emptyBucket` function. With no items containing the keyPrefix, the keyPrefix logic resulted in an empty array of S3 objects being passed to the `deleteObjects` S3 request. This fix resolves the promise if there are no objects to delete.
=> Fix bucket deletion when using keyPrefix

README.md, index.js, lib/configure.js
Issue #95 -add support for tagging of buckets.
Passing a tags object into a custom function and calling the aws cli putBucketTags command to set them
[@ mentions of other contributors]
=> Tag support

index.js
Current usage is quite misleading as this text can be interpreted as it will overwrite the whole bucket.
=> Add keyprefix to deployDescribe log

index.js, package-lock.json, package.json
https://github.com/fernando-mc/serverless-finch/issues/130
package.json needs to be updated to use set-value@4.0.1 or above. Since set-value was not used by this project directly, the dependencies that do use it had to be updated to the the latest versions that do not have this issue.
For more information see https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-23440.
=> fix: upgrade dependencies not use use set-value versions below 4.0.1

.czrc, .github/workflows/integration-test.yml, .github/workflows/release.yml, .gitignore, .husky/commit-msg, .husky/pre-commit, .lintstagedrc.json, .mocharc.json, CONTRIBUTING.md, commitlint.config.js, package-lock.json, package.json
Replaces the `publish` action with a `release` action using [semantic-release](https://github.com/semantic-release/semantic-release). The `semantic-release` tool will generate a release and publish to NPM out-of-the-box, no configuration necessary.
The action is set up so it must be [run manually](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow). 
* semantic-release takes care of updating the `package.json` version before publishing to npm, so the version on source control is no longer used. [FAQ](https://github.com/semantic-release/semantic-release/blob/master/docs/support/FAQ.md)
* the github action references GITHUB_TOKEN env var - but according to these [docs](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configur …
=> Automate release process + misc chores

.prettierrc, index.js
In Serverless 3, `serverles.cli.log` is [deprecated](https://www.serverless.com/framework/docs/guides/plugins/cli-output#writing-to-the-output).  This PR simply changes over to use the recommended log method.
It also includes a change to the Prettier configuration to preserve the same formatting that was present before Prettier was upgraded to v2. Eventually maybe we want to change this config, but better to do that in a separate PR where all files are reformatted.
=> Don't use deprecated log method

lib/plugin.js
Fixes a small issue when no keyPrefix is specified, the log output would include "undefined":
```
This deployment will:
- Upload all files from 'client\dist' to bucket 'my-bucket' undefined
```
=> fix(log): don't log undefined string

lib/bucket-utils.js
ensure that deletePublicAccessBlock is allowed to run before moving on from bucket creation.
Following on from the fix I did a few days ago around the breaking S3 policy change, I missed a return here to ensure that the `deletePublicAccessBlock` call is completed before moving on. We still see occasional errors owing to this race condition.
=> fix(bucket-utils): small fix for async race condition

lib/validate.js, lib/validate.test.js
=> fix: check for undefined options when validating
